title: Jessica Xu
description: Welcome to my page!
author: Jessica Xu
show_downloads: false
google_analytics:
theme: jekyll-theme-architect

# Navigation menu
nav_links:
  - title: "About Me"
    url: /about-me
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact
